### ISSUE TITLE
请添加新的镜像站

### ISSUE THREAD

**Issue by magojohnji** [jia110/jia110.github.io#4]
https://g.luciaz.me/ (这个还是浙大的，问题答案分别是 心灵之约、水朝夕、csxy@123)
http://google.lyz810.com/
https://google.icloudnative.io/ (算是自定义界面，挺好看的)
http://google.1qi777.com/
https://gogogle.cf/
《!-- 这里有一个貌似抄袭的网站 https://mirror.js.org/ --》

**Comment by jia110** [comment]
非常感谢您提供的镜像站链接  该站开源共享 不存在抄袭问题 只要能为科研人员提供帮助就行
