### ISSUE TITLE
反馈+推荐

### ISSUE THREAD

**Issue by Nangjing** [jia110/jia110.github.io#5]
google.pem.app挂了，现在是pem.app

然后推荐几个google镜像：

http://d.6wl.cc/   
https://xgoogle.xyz/  （这个主页改过）
https://g.qwq.fan/
https://g.xzx725.top/
https://txt.muxinghe.cf/
https://goo.xbzxs.org/

你这里谷歌搜索镜像也太少了😂

**Comment by jia110** [comment]
感谢分享  的确很少 和谐的快 近期也很少有时间弄 感谢
