### ISSUE TITLE
新镜像站

### ISSUE THREAD

**Issue by magojohnji** [jia110/jia110.github.io#6]
我又来了
Google：https://谷歌.ml/ (也就是https://xn--flw351e.ml/)
Github的全挂了，新的：https://hub.njuu.cf/ | https://hub.yzuu.cf/ | https://hub.nuaa.cf/ 
（下面不是有个https://www.library.ac.cn/的镜像站网址嘛，有时候去那里面抄一点【Doge】）

**Comment by jia110** [comment]
哈哈 行有时间我去抄一点 最近疫情实验室忙 已经更新了 感谢
